### ISSUE TITLE
3.x and 4.x : Use smaller EC2 instances 

### ISSUE THREAD

**Issue by pranavgaikwad** [fusor/mig-agnosticd#17]
Current instance configurations : 

OCP 3 : 
- infranode x 1 (m4.4xlarge)
- node x 2 (m4.4xlarge)
- master x 1 (m4.4xlarge)
- support x 1 (m4.4xlarge)
- bastion x 1 (t2.large)

OCP 4 : 
- master x 3 (m4.xlarge)
- worker x 3 (m4.4xlarge)
- bootstrap x 1 (m4.large)

Investigate if we can use smaller instances. 

For OCP 4, investigate if three masters are required.

**Comment by pranavgaikwad** [comment]
OCP 3 configuration variables : 

Looking at https://github.com/redhat-cop/agnosticd/blob/development/ansible/configs/ocp-workshop/env_vars.yml : 

```yaml
bastion_instance_type: "t2.large"
master_instance_type: "m4.4xlarge"
etcd_instance_type: "{{master_instance_type}}"
infranode_instance_type: "m4.4xlarge"
node_instance_type: "m4.4xlarge"
support_instance_type: "m4.4xlarge"
nfs_instance_type: "{{ support_instance_type }}"
```
